version: '3'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-4
    restart: always
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
#    volumes:
#      - postgresql_data:/var/lib/postgresql

  redmine:
    depends_on:
      - postgresql
    image: sameersbn/redmine:4.0.3-1
    restart: always
    environment:
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
      - REDMINE_PORT=10083
    ports:
      - "10083:80"
    volumes:
      - /home/redmine/data

#volumes:
#  postgresql_data:
#  redmine_data:
