version: '3'

services:
  db:
    image: e1ee1e11/postgresql_armhf:9.4.8-1
    volumes:
      - ${PWD}/flash/postgres_folder:/media/postgres_folder
    environment:
      - POSTGRES_USER=openerp_8
      - POSTGRES_PASSWORD=qwerty

  web:
    depends_on:
      - db
    image: e1ee1e11/arm-odoo:8.0
    user: openerp_user
    volumes:
      - ${PWD}/odoo_addons:/opt/openerp_8/my_addons
    ports:
      - "18069:8069"
    environment:
      - POSTGRES_USER=openerp_8
      - POSTGRES_PASSWORD=qwerty
