version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
#    volumes:
#      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla

  joomla:
    depends_on:
      - db
    image: joomla:3.9.5
    restart: always
    ports:
      - "10082:80"
    volumes:
      - ./database.xml:/var/www/html/installation/model/forms/database.xml
    environment:
      JOOMLA_DB_HOST: db:3306
      JOOMLA_DB_PASSWORD: example

#volumes:
#  db_data:
